spring.application.name=demo
# H2 数据库配置（文件模式，存到项目根目录的 ./data 文件夹）
spring.datasource.url=jdbc:h2:file:./data/blog;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA 配置（自动创建表结构）
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

github.token=${GITHUB_TOKEN}
github.username=white66-7